.PHONY: clean All

All:
	@echo "----------Building project:[ StatementsAndOperators - Debug ]----------"
	@cd "StatementsAndOperators" && "$(MAKE)" -f  "StatementsAndOperators.mk"
clean:
	@echo "----------Cleaning project:[ StatementsAndOperators - Debug ]----------"
	@cd "StatementsAndOperators" && "$(MAKE)" -f  "StatementsAndOperators.mk" clean
