.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayExcercise - Debug ]----------"
	@cd "ArrayExcercise" && "$(MAKE)" -f  "ArrayExcercise.mk"
clean:
	@echo "----------Cleaning project:[ ArrayExcercise - Debug ]----------"
	@cd "ArrayExcercise" && "$(MAKE)" -f  "ArrayExcercise.mk" clean
