.PHONY: clean All

All:
	@echo "----------Building project:[ SwitchStatement - Debug ]----------"
	@cd "SwitchStatement" && "$(MAKE)" -f  "SwitchStatement.mk"
clean:
	@echo "----------Cleaning project:[ SwitchStatement - Debug ]----------"
	@cd "SwitchStatement" && "$(MAKE)" -f  "SwitchStatement.mk" clean
