.PHONY: clean All

All:
	@echo "----------Building project:[ Epanaliptiko - Debug ]----------"
	@cd "Epanaliptiko" && "$(MAKE)" -f  "Epanaliptiko.mk"
clean:
	@echo "----------Cleaning project:[ Epanaliptiko - Debug ]----------"
	@cd "Epanaliptiko" && "$(MAKE)" -f  "Epanaliptiko.mk" clean
